apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: enact-dev
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 32554
      hostPort: 35554
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 32580
      hostPort: 35580
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 32585
      hostPort: 35555
      listenAddress: "0.0.0.0"
      protocol: TCP
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
